apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqusers.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: RabbitMQUser
    plural: rabbitmqusers
    singular: rabbitmquser
    shortNames:
      - rbu
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                username:
                  description: The username
                  type: string
                password:
                  description: The secret containing the password of the user
                  type: object
                  properties:
                    key:
                      description: The key of the secret to select from.  Must
                        be a valid secret key.
                      type: string
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                      type: string
                vhost:
                  description: Authorized vhost
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true