apiVersion: v1
kind: Secret
metadata:
metadata:
  name: {{ include "rabbitmq-management-operator.fullname" . }}
  labels:
    {{- include "rabbitmq-management-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_USER: {{ .Values.rabbitmq.user }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password }}
  RABBITMQ_URL: {{ .Values.rabbitmq.managementUrl }}
  RABBITMQ_VERIFY: "{{ .Values.rabbitmq.verify | toString}}"
